### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: req.files.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by QKTheoNguyen** [gazugafan/AutoLyrixAlignService#9]
Hello Gazugafan, 

Thank you for your work !
Unfortunately, I encountered a problem when requesting an alignment, here is the following message: 

```
Received an alignment request!
(node:23796) UnhandledPromiseRejectionWarning: TypeError: req.files.hasOwnProperty is not a function
    at index (/root/AutoLyrixAlignService/align.js:20:70)
    at Layer.handle [as handle_request] (/root/AutoLyrixAlignService/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/AutoLyrixAlignService/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/root/AutoLyrixAlignService/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/root/AutoLyrixAlignService/node_modules/express/lib/router/layer.js:95:5)
    at /root/AutoLyrixAlignService/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/root/AutoLyrixAlignService/node_modules/express/lib/router/index.js:346:12)
    at next (/root/AutoLyrixAlignService/node_modules/express/lib/router/index.js:280:10)
    at /root/AutoLyrixAlignService/node_modules/express-fileupload/lib/processMultipart.js:158:9
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Could you help me understand what it means ?

Thank you very much !

**Comment by gazugafan** [comment]
Hmm, not sure. My first thought is maybe a bad version of node? What version of node are you running?
